// File: JavaScript/Constants.js
// Description: Holds all static data, constants, and definitions for the app.

// --- Cube State Constants ---
const CUBEL = 24;
const HALF_L = 6;
const LAYERL = 12;
const THREE_FOUR_L = 18;
const SOLVED_a = "BBbBBbBBbBBbWWwWWwWWwWWw";
const SOLVED_A = "bBBbBBbBBbBBwWWwWWwWWwWW";
const SLICE_a = "WWwWWwBBbBBbBBbBBbWWwWWw";
const SLICE_A = "wWWwWWbBBbBBbBBbBBwWWwWW";

// --- OBL Case Definitions ---
const OBL = {
  "1c": "BBwWWwWWwWWw",
  cadj: "BBwBBwWWwWWw",
  copp: "BBwWWwBBwWWw",
  "3c": "BBwBBwBBwWWw",
  "4e": "BBwBBwBBwBBw",
  "3e": "WWbWWbWWbWWw",
  line: "WWbWWwWWbWWw",
  L: "WWbWWbWWwWWw",
  "1e": "WWbWWwWWwWWw",
  "left pair": "WWbBBwWWwWWw",
  "right pair": "BBbWWwWWwWWw",
  "left arrow": "BBwWWwWWbWWw",
  "right arrow": "BBwWWbWWwWWw",
  gem: "WWbBBbWWwWWw",
  "left knight": "WWwWWbWWbBBw",
  "right knight": "BBbWWbWWwWWw",
  "left axe": "WWwWWbWWwBBb",
  "right axe": "BBwWWbWWwWWb",
  squid: "BBwWWbWWbWWw",
  "left thumb": "WWwWWbBBbWWb",
  "right thumb": "WWbBBbWWwWWb",
  "left bunny": "WWwBBbWWbWWb",
  "right bunny": "WWbWWbBBwWWb",
  shell: "BBbBBwWWwWWw",
  "left bird": "BBwWWwWWbBBw",
  "right bird": "BBwBBbWWwWWw",
  hazard: "BBwWWbWWwBBw",
  "left kite": "BBbBBbWWwWWw",
  "right kite": "WWwWWbBBbBBw",
  "left cut": "BBwBBwWWbWWb",
  "right cut": "BBwBBbWWbWWw",
  "black T": "BBbBBwWWbWWw",
  "white T": "WWwWWbBBwBBb",
  "left N": "WWbBBwWWbBBw",
  "right N": "WWwBBbWWwBBb",
  "black tie": "WWbBBbWWwBBw",
  "white tie": "BBwWWwBBbWWb",
  "left yoshi": "BBbWWwBBwWWw",
  "right yoshi": "WWwBBwWWbBBw",
};

// --- Karnaugh Notation & Moves ---
const KARN = {
  "3,0": "U",
  "-3,0": "U'",
  "0,3": "D",
  "0,-3": "D'",
  "3,3": "e",
  "2,-1": "u",
  "-1,2": "d",
  "-4,-1": "F'",
  "-1,-4": "f'",
  "2,-4": "T",
  "2,2": "m",
  "-1,-1": "M'",
  "5,-1": "u2",
  "-2,1": "u'",
  "1,-2": "d'",
  "4,1": "F",
  "1,4": "f",
  "-2,4": "T'",
  "-2,-2": "m'",
  "1,1": "M",
  "-5,1": "u2'",
};
const A_MOVES = [
  [3, 0],
  [-3, 0],
  [0, 3],
  [0, -3],
  [3, 3],
  [2, -1],
  [-1, 2],
  [-4, -1],
  [-1, -4],
  [2, -4],
  [2, 2],
  [-1, -1],
  [5, -1],
];
const a_MOVES = [
  [3, 0],
  [-3, 0],
  [0, 3],
  [0, -3],
  [3, 3],
  [-2, 1],
  [1, -2],
  [4, 1],
  [1, 4],
  [-2, 4],
  [-2, -2],
  [1, 1],
  [-5, 1],
];
const KARNL = a_MOVES.length;

// --- Advanced Notation ---
const HIGHKARN = {
  "U U' U U' ": "U4 ",
  "U' U U' U ": "U4' ",
  "D D' D D' ": "D4 ",
  "D' D D' D ": "D4' ",
  "u u' u u' ": "u4 ",
  "u' u u' u ": "u4' ",
  "d d' d d' ": "d4 ",
  "d' d d' d ": "d4' ",
  "U U' U ": "U3 ",
  "U' U U' ": "U3' ",
  "D D' D ": "D3 ",
  "D' D D' ": "D3' ",
  "u u' u ": "u3 ",
  "u' u u' ": "u3' ",
  "d d' d ": "d3 ",
  "d' d d' ": "d3' ",
  "F F' F ": "F3 ",
  "F' F F' ": "F3' ",
  "f f' f ": "f3 ",
  "f' f f' ": "f3' ",
  "U U' ": "W ",
  "U' U ": "W' ",
  "D D' ": "B ",
  "D' D ": "B' ",
  "u u' ": "w ",
  "u' u ": "w' ",
  "d d' ": "b ",
  "d' d ": "b' ",
  "F F' ": "F2 ",
  "F' F ": "F2' ",
  "f f' ": "f2 ",
  "f' f ": "f2' ",
  "U U ": "UU ",
  "U' U' ": "UU' ",
  "D D ": "DD ",
  "D' D' ": "DD' ",
  "60 ": "U2 ",
  "63 ": "U2D ",
  "6-3 ": "U2D' ",
  "66 ": "U2D2 ",
  "06 ": "D2 ",
  "36 ": "UD2",
  "-36 ": "U'D2",
};

// --- Scramble Optimizations ---
const OPTIM = {
  "/3,3/3,3/": "-3,-3/-3,-3",
  "/-3,-3/-3,-3/": "3,3/3,3",
  "/2,2/-2,-2/": "2,2/-2,-2",
  "/-2,-2/2,2/": "-2,-2/2,2",
  "/1,1/-1,-1/": "1,1/-1,-1",
  "/-1,-1/1,1/": "-1,-1/1,1",
  "/2,-4/-2,4/2,-4/": "2,-4/-2,4/2,-4",
  "/-2,4/2,-4/-2,4/": "-2,4/2,-4/-2,4",
  "/5,-1/-5,1/5,-1/": "5,-1/-5,1/5,-1",
  "/-5,1/5,-1/-5,1/": "-5,1/5,-1/-5,1",
};
const OPTIM_KEYS = Array.from(Object.keys(OPTIM));

// --- *** OBL Case Groups (CORRECTED) *** ---
// All case names are lowercase and match OBLtranslation keys.
const OBL_GROUPS = {
  "1 Slicer": [
    ["good", "kite", "kite"], // Corrected format
  ],
  "2 Slicers": [
    ["", "copp", "copp"],
    ["", "line", "line"],
    ["good", "thumb", "thumb"],
    ["good", "pair", "pair"],
    ["good", "N", "N"],
  ],
  "3 Slicers": [
    ["good", "arrow", "pair"],
    ["good", "arrow", "arrow"],
    ["", "gem", "axe"],
    ["good", "knight", "axe"],
    ["good", "bunny", "bunny"],
    ["good", "yoshi", "bird"],
    ["", "yoshi", "shell"],
    ["good", "kite", "cut"],
    ["good", "kite", "N"],
    ["good", "cut", "cut"],
    ["good", "T", "T"],
    ["good", "T", "tie"],
    ["good", "tie", "tie"],
  ],
  "4 Slicers": [
    ["", "cadj", "cadj"],
    ["", "4e", "4e"],
    ["", "L", "L"],
    ["bad", "pair", "pair"],
    ["bad", "arrow", "pair"],
    ["bad", "arrow", "arrow"],
    ["", "gem", "gem"],
    ["", "gem", "knight"],
    ["", "gem", "squid"],
    ["good", "knight", "knight"],
    ["bad", "knight", "axe"],
    ["", "squid", "axe"],
    ["", "squid", "knight"],
    ["good", "thumb", "bunny"],
    ["bad", "thumb", "bunny"],
    ["", "shell", "shell"],
    ["", "shell", "bird"],
    ["", "shell", "hazard"],
    ["good", "bird", "bird"],
    ["", "bird", "hazard"],
    ["bad", "yoshi", "bird"],
    ["", "yoshi", "hazard"],
    ["", "kite", "T"],
    ["bad", "kite", "N"],
    ["", "kite", "tie"],
    ["", "cut", "T"],
    ["good", "cut", "N"],
    ["", "cut", "tie"],
    ["bad", "T", "T"],
    ["bad", "T", "tie"],
    ["bad", "N", "N"],
    ["bad", "tie", "tie"],
  ],
  "5 Slicers": [
    ["", "1c", "1c"],
    ["", "cadj", "copp"],
    ["", "3c", "3c"],
    ["", "3e", "3e"],
    ["", "L", "line"],
    ["", "1e", "1e"],
    ["bad", "knight", "knight"],
    ["good", "axe", "axe"],
    ["bad", "axe", "axe"],
    ["", "squid", "squid"],
    ["bad", "thumb", "thumb"],
    ["bad", "bunny", "bunny"],
    ["bad", "bird", "bird"],
    ["", "hazard", "hazard"],
    ["good", "yoshi", "yoshi"],
    ["bad", "yoshi", "yoshi"],
    ["bad", "kite", "kite"],
    ["bad", "cut", "N"],
    ["", "T", "N"],
    ["", "tie", "N"],
  ],
  "6 Slicers": [
    ["bad", "kite", "cut"],
    ["bad", "cut", "cut"],
  ],
};

/**
 * Helper function to get a flat array of all OBL cases from the groups.
 * @returns {Array<Array<string>>} A flat array of all OBL cases.
 */
function getAllOblCases() {
  let allCases = [];
  for (const cases of Object.values(OBL_GROUPS)) {
    // Using the correct variable name
    allCases.push(...cases);
  }
  return allCases;
}

// --- App Data: OBL Case Translations ---
const OBLtranslation = {
  "1c/1c": ["1c/1c"],
  "cadj/cadj": ["cadj/cadj"],
  "cadj/copp": ["cadj/copp"],
  "copp/copp": ["copp/copp"],
  "3c/3c": ["3c/3c"],
  "4e/4e": ["4e/4e"],
  "3e/3e": ["3e/3e"],
  "line/line": ["line/line"],
  "L/line": ["L/line"],
  "L/L": ["L/L"],
  "1e/1e": ["1e/1e"],
  "good pair/pair": ["left pair/left pair", "right pair/right pair"],
  "bad pair/pair": ["left pair/right pair"],
  "good arrow/pair": ["left arrow/right pair", "right arrow/left pair"],
  "bad arrow/pair": ["left arrow/left pair", "right arrow/right pair"],
  "good arrow/arrow": ["left arrow/left arrow", "right arrow/right arrow"],
  "bad arrow/arrow": ["left arrow/right arrow"],
  "gem/gem": ["gem/gem"],
  "gem/knight": ["gem/left knight", "gem/right knight"],
  "gem/axe": ["gem/left axe", "gem/right axe"],
  "gem/squid": ["gem/squid"],
  "good knight/knight": ["left knight/right knight"],
  "bad knight/knight": ["left knight/left knight", "right knight/right knight"],
  "good knight/axe": ["left knight/left axe", "right knight/right axe"],
  "bad knight/axe": ["left knight/right axe", "right knight/left axe"],
  "good axe/axe": ["left axe/left axe", "right axe/right axe"],
  "bad axe/axe": ["left axe/right axe"],
  "squid/knight": ["squid/left knight", "squid/right knight"],
  "squid/axe": ["squid/left axe", "squid/right axe"],
  "squid/squid": ["squid/squid"],
  "good thumb/thumb": ["left thumb/left thumb", "right thumb/right thumb"],
  "bad thumb/thumb": ["left thumb/right thumb"],
  "good thumb/bunny": ["left thumb/right bunny", "right thumb/left bunny"],
  "bad thumb/bunny": ["left thumb/left bunny", "right thumb/right bunny"],
  "good bunny/bunny": ["left bunny/left bunny", "right bunny/right bunny"],
  "bad bunny/bunny": ["left bunny/right bunny"],
  "shell/shell": ["shell/shell"],
  "shell/bird": ["shell/left bird", "shell/right bird"],
  "shell/hazard": ["shell/hazard"],
  "yoshi/shell": ["left yoshi/shell", "right yoshi/shell"],
  "good bird/bird": ["left bird/right bird"],
  "bad bird/bird": ["left bird/left bird", "right bird/right bird"],
  "bird/hazard": ["left bird/hazard", "right bird/hazard"],
  "hazard/hazard": ["hazard/hazard"],
  "good yoshi/bird": ["left yoshi/left bird", "right yoshi/right bird"],
  "bad yoshi/bird": ["left yoshi/right bird", "right yoshi/left bird"],
  "yoshi/hazard": ["left yoshi/hazard", "right yoshi/hazard"],
  "good yoshi/yoshi": ["left yoshi/left yoshi", "right yoshi/right yoshi"],
  "bad yoshi/yoshi": ["left yoshi/right yoshi"],
  "good kite/kite": ["left kite/left kite", "right kite/right kite"],
  "bad kite/kite": ["left kite/right kite"],
  "good kite/cut": ["left kite/left cut", "right kite/right cut"],
  "bad kite/cut": ["left kite/right cut", "right kite/left cut"],
  "kite/T": [
    "left kite/black T",
    "left kite/white T",
    "right kite/black T",
    "right kite/white T",
  ],
  "good kite/N": ["left kite/right N", "right kite/left N"],
  "bad kite/N": ["left kite/left N", "right kite/right N"],
  "kite/tie": [
    "left kite/black tie",
    "left kite/white tie",
    "right kite/black tie",
    "right kite/white tie",
  ],
  "cut/T": [
    "left cut/black T",
    "left cut/white T",
    "right cut/black T",
    "right cut/white T",
  ],
  "good cut/N": ["left cut/left N", "right cut/right N"],
  "bad cut/N": ["left cut/right N", "right cut/left N"],
  "cut/tie": [
    "left cut/black tie",
    "left cut/white tie",
    "right cut/black tie",
    "right cut/white tie",
  ],
  "good cut/cut": ["left cut/left cut", "right cut/right cut"],
  "bad cut/cut": ["left cut/right cut"],
  "good T/T": ["black T/black T", "white T/white T"],
  "bad T/T": ["black T/white T"],
  "T/N": [
    "black T/left N",
    "black T/right N",
    "white T/left N",
    "white T/right N",
  ],
  "good T/tie": ["black T/black tie", "white T/white tie"],
  "bad T/tie": ["black T/white tie", "white T/black tie"],
  "good N/N": ["left N/left N", "right N/right N"],
  "bad N/N": ["left N/right N"],
  "tie/N": [
    "black tie/left N",
    "black tie/right N",
    "white tie/left N",
    "white tie/right N",
  ],
  "good tie/tie": ["black tie/black tie", "white tie/white tie"],
  "bad tie/tie": ["black tie/white tie"],
};

// --- App Timer Constants ---
const MIN_EACHCASE = 2;
const MAX_EACHCASE = 4;
const startDelay = 0;
